services:
  broker1:
    image: apache/kafka:latest
    hostname: broker1
    container_name: broker1
    restart: unless-stopped
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker1:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_LOG_RETENTION_MS: "9000000"
      KAFKA_LOG_RETENTION_BYTES: "2147483648"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker1:29093
      KAFKA_LISTENERS: PLAINTEXT://broker1:29092,CONTROLLER://broker1:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs-1
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    healthcheck:
      test: [ "CMD", "sh", "-c", "nc -z broker1 29092 || exit 1" ]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - test_network

#  hbase:
#    image: harisekhon/hbase
#    container_name: hbase
#    hostname: hbase
#    networks:
#      - test_network
#    ports:
#      - "16010:16010"
#      - "16020:16020"
#      - "2181:2181"
#      - "9090:9090"

#  cassandra_1:
#    image: cassandra:4.1
#    container_name: cassandra_1
#    hostname: cassandra_1
#    networks:
#      - test_network
#    environment:
#      CASSANDRA_CLUSTER_NAME: test-cluster
#      CASSANDRA_SEEDS: cassandra_1
#      CASSANDRA_DC: dc1
#      CASSANDRA_RACK: rack1
#      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
#    volumes:
#      - ./volume/cassandra/node_1:/var/lib/cassandra
#    ports:
#      - "9042:9042"
#      - "7000:7000"
#    restart: unless-stopped
#
#  cassandra_2:
#    image: cassandra:4.1
#    container_name: cassandra_2
#    hostname: cassandra_2
#    networks:
#      - test_network
#    environment:
#      CASSANDRA_CLUSTER_NAME: test-cluster
#      CASSANDRA_SEEDS: cassandra_1
#      CASSANDRA_DC: dc1
#      CASSANDRA_RACK: rack1
#      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
#    volumes:
#      - ./volume/cassandra/node_2:/var/lib/cassandra
#    depends_on:
#      - cassandra_1
#    restart: unless-stopped


networks:
  test_network:
     driver: bridge
