apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: bigdata
data:
  app_config.yaml: |
    kafka:
      bootstrap_servers: "kafka-service.bigdata.svc.cluster.local:9092"
      topic: "flight_sensor_data"
    paths:
      local_source_data: "data/T_ONTIME_REPORTING_2025_M6.csv"
      hdfs_raw_data: "s3a://warehouse/data/raw/flights/"
      hdfs_checkpoint: "s3a://warehouse/checkpoints/ingestion/"

    minio_config:
      endpoint: "http://minio-service.bigdata.svc.cluster.local:9000"
      access_key: "admin"
      secret_key: "password123"
      bucket: "warehouse"

    database:
      url: "postgresql://neondb_owner:npg_LK04qASEgCyc@ep-still-shadow-ahdpmoze-pooler.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
      csv: "./data/T_ONTIME_REPORTING_2025_M1.csv"
